In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("demo_movie.csv")
df

,movie_id,title,vote_average,popularity,vote_count,budget,revenue,runtime,genres,keywords,companies,languages,countries
0,99,NaN,8.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,Avatar,7.8,82.3,15000.0,237000000.0,2.800000e+09,162.0,NaN,rebellion,20th Century Fox,English,United States
2,1,Inception,8.8,90.2,21000.0,160000000.0,8.290000e+08,148.0,"Action, Science Fiction",dream,Warner Bros.,English,United States
3,2,The Matrix,8.7,88.5,18000.0,63000000.0,4.650000e+08,136.0,Action,virtual reality,Warner Bros.,English,United States
4,3,Interstellar,8.6,85.0,19500.0,165000000.0,6.770000e+08,169.0,"Science Fiction, Adventure",space,Legendary Pictures,English,United States
5,5,Spirited Away,8.5,75.6,13000.0,15000000.0,3.550000e+08,125.0,Fantasy,magic,Studio Ghibli,Japanese,Japan
6,6,The Godfather,9.2,70.1,21000.0,6000000.0,2.460000e+08,175.0,Crime,mafia,Paramount Pictures,English,United States
7,7,The Dark Knight,9.0,95.0,22000.0,185000000.0,1.005000e+09,152.0,"Action, Crime",joker,Warner Bros.,English,United States
8,8,Parasite,8.6,78.3,14000.0,11400000.0,2.580000e+08,132.0,Drama,class divide,Barunson E&A,Korean,South Korea
9,9,The Shawshank Redemption,9.3,85.7,24000.0,25000000.0,7.300000e+07,142.0,Drama,prison,Castle Rock Entertainment,English,United States
10,10,The Lion King,8.5,80.0,17000.0,45000000.0,9.680000e+08,88.0,Animation,lion,Disney,English,United States

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      11 non-null     int64
 1   title         10 non-null     object
 2   vote_average  11 non-null     float64
 3   popularity    10 non-null     float64
 4   vote_count    10 non-null     float64
 5   budget        10 non-null     float64
 6   revenue       10 non-null     float64
 7   runtime       10 non-null     float64
 8   genres        9 non-null      object
 9   keywords      10 non-null     object
 10  companies     10 non-null     object
 11  languages     10 non-null     object
 12  countries     10 non-null     object
dtypes: float64(6), int64(1), object(6)
memory usage: 1.2+ KB