In [1]:
#!pip install lightfm

# Import Dataset

In [2]:
import pandas as pd

MOVIE_METADATA_PATH = "movie_enriched_view.csv"
USER_RATINGS_PATH = "user_ratings_200users_30each.csv"
movies_df = pd.read_csv(MOVIE_METADATA_PATH)
users_df = pd.read_csv(USER_RATINGS_PATH)

In [3]:
movies_df.head()

,movie_id,status,title,adult,original_language,release_date,vote_count,vote_average,popularity,budget,revenue,runtime,genres,keywords,companies,languages,countries
0,826740,Released,Three Songs for Benazir,False,ps,2021-06-02 00:00:00 UTC,51,6.206,3.021,0,0,22,Documentary,"poverty, poor, young love, afghanistan",Mirzaei Films,Pushto,afghanistan
1,319998,Released,Sworn Virgin,False,it,2015-03-19 00:00:00 UTC,50,5.440,2.893,0,0,87,Drama,woman director,"Colorado Film, Bord Cadre Films, Vivo Film, Th...","Italian, Albanian","albania, switzerland, germany, italy"
2,593655,Released,Castle Freak,False,en,2020-12-04 00:00:00 UTC,56,4.429,10.141,0,0,106,Horror,"trauma, monster, madness, prisoner, castle, di...","Full Moon Entertainment, Pioneer Media, Ill Wi...",English,"albania, united states of america"
3,82624,Released,The Forgiveness of Blood,False,en,2011-02-18 00:00:00 UTC,36,6.600,4.665,0,0,109,Drama,"seclusion, blood feud, vendetta","Journeyman Pictures, Lissus Media, Fandango, C...",Albanian,"albania, united states of america, united king..."
4,49321,Released,Brancaleone at the Crusades,False,it,1970-12-24 00:00:00 UTC,132,7.117,5.961,0,0,120,"Adventure, Comedy","brancaleone, crusade, medieval","Fair Film, Office National pour le Commerce et...",Italian,"algeria, italy"

In [4]:
movies_df[movies_df["movie_id"] == 386564]

,movie_id,status,title,adult,original_language,release_date,vote_count,vote_average,popularity,budget,revenue,runtime,genres,keywords,companies,languages,countries
101526,386564,Released,"Hang in There, Kids!",False,zh,2016-03-18 00:00:00 UTC,4,5.75,0.989,0,0,90,"Drama, Family, Comedy",woman director,"Sun Moon Stars Entertainment, Sky Films Entert...",Mandarin,taiwan

In [5]:
users_df.head()

,user_id,movie_id,title,genres,keywords,rating,combined
0,user_1,386564,"Hang in There, Kids!","Drama, Family, Comedy",woman director,3.08,NaN
1,user_1,67077,The Plane Tree,"Drama, Family, Comedy",woman director,3.59,NaN
2,user_1,189005,Pennies from Heaven,"Drama, Music, Comedy","welfare, singer, welfare worker",2.91,NaN
3,user_1,154764,Miyamoto Musashi,"Drama, History, Action","jidaigeki, miyamoto musashi, chambara",3.20,NaN
4,user_1,512062,Vinayapoorvam Vidyadharan,"Drama, Family, Comedy","dysfunctional marriage, romance",3.79,NaN

In [6]:
import pandas as pd

def check_data_quality(df):
    print("✅ Data Overview")
    print("-" * 40)
    print(f"🧾 Shape: {df.shape}")
    print("\n📌 Column Info:")
    display(df.dtypes)

    print("\n🔍 Missing Values (per column):")
    display(df.isnull().sum())

    print("\n📎 Duplicated Rows:", df.duplicated().sum())

    print("\n🔢 Non-null Count & Types:")
    display(df.info())

    print("\n📊 Basic Statistics (numeric columns):")
    display(df.describe())

    print("\n🧪 Sample Rows:")
    display(df.sample(5))

In [7]:
check_data_quality(movies_df)

✅ Data Overview
----------------------------------------
🧾 Shape: (135886, 17)

📌 Column Info:

movie_id               int64
status                object
title                 object
adult                   bool
original_language     object
release_date          object
vote_count             int64
vote_average         float64
popularity           float64
budget                 int64
revenue                int64
runtime                int64
genres                object
keywords              object
companies             object
languages             object
countries             object
dtype: object

🔍 Missing Values (per column):

movie_id              0
status                0
title                 0
adult                 0
original_language     0
release_date          0
vote_count            0
vote_average          0
popularity            0
budget                0
revenue               0
runtime               0
genres                0
keywords              0
companies            13
languages             0
countries             0
dtype: int64

📎 Duplicated Rows: 0

🔢 Non-null Count & Types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135886 entries, 0 to 135885
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   movie_id           135886 non-null  int64
 1   status             135886 non-null  object
 2   title              135886 non-null  object
 3   adult              135886 non-null  bool
 4   original_language  135886 non-null  object
 5   release_date       135886 non-null  object
 6   vote_count         135886 non-null  int64
 7   vote_average       135886 non-null  float64
 8   popularity         135886 non-null  float64
 9   budget             135886 non-null  int64
 10  revenue            135886 non-null  int64
 11  runtime            135886 non-null  int64
 12  genres             135886 non-null  object
 13  keywords           135886 non-null  object
 14  companies          135873 non-null  object
 15  languages          135886 non-null  object
 16  countries          135886 non-null  object
dtypes: bool(1), float64(2), int64(5), object(9)
memory usage: 16.7+ MB

None

📊 Basic Statistics (numeric columns):

,movie_id,vote_count,vote_average,popularity,budget,revenue,runtime
count,1.358860e+05,135886.000000,135886.000000,135886.000000,1.358860e+05,1.358860e+05,135886.000000
mean,4.137219e+05,140.003481,4.488861,4.183367,1.821721e+06,4.854804e+06,77.655527
std,3.581524e+05,888.456058,2.972461,20.250997,1.198784e+07,4.313858e+07,46.001031
min,2.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000
25%,1.063838e+05,0.000000,0.000000,0.654000,0.000000e+00,0.000000e+00,53.000000
50%,3.364875e+05,4.000000,5.541000,1.400000,0.000000e+00,0.000000e+00,87.000000
75%,6.043425e+05,21.000000,6.624000,3.579750,0.000000e+00,0.000000e+00,100.000000
max,1.491305e+06,32571.000000,10.000000,2994.357000,4.600000e+08,2.068224e+09,1265.000000

🧪 Sample Rows:

,movie_id,status,title,adult,original_language,release_date,vote_count,vote_average,popularity,budget,revenue,runtime,genres,keywords,companies,languages,countries
54930,471684,Released,Orders Is Orders,False,en,1933-07-18 00:00:00 UTC,0,0.000,1.304,0,0,62,Comedy,army base,Gaumont-British Picture Corporation,English,united kingdom
34742,673755,Released,Profile of a Problem Drinker,False,en,1957-01-02 00:00:00 UTC,0,0.000,0.600,0,0,29,Drama,alcoholism,ONF | NFB,English,canada
58397,475090,Released,The Courtship of the Newt,False,en,1938-07-22 00:00:00 UTC,0,0.000,0.600,0,0,8,Comedy,short film,Metro-Goldwyn-Mayer,English,united states of america
64788,807896,Released,Lesbian House Hunters 10,True,en,2015-03-13 00:00:00 UTC,0,0.000,0.600,0,0,152,Romance,lesbian sex,Girlfriends Films,English,united states of america
23974,31726,Released,"Be My Valentine, Charlie Brown",False,en,1975-01-28 00:00:00 UTC,68,6.743,9.693,0,0,25,"TV Movie, Family, Animation","valentine's day, holiday","Lee Mendelson Film Productions, Bill Melendez ...",English,united states of america

In [8]:
check_data_quality(users_df)

✅ Data Overview
----------------------------------------
🧾 Shape: (6000, 7)

📌 Column Info:

user_id      object
movie_id      int64
title        object
genres       object
keywords     object
rating      float64
combined     object
dtype: object

🔍 Missing Values (per column):

user_id        0
movie_id       0
title          0
genres         0
keywords       0
rating         0
combined    5000
dtype: int64

📎 Duplicated Rows: 0

🔢 Non-null Count & Types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   user_id   6000 non-null   object
 1   movie_id  6000 non-null   int64
 2   title     6000 non-null   object
 3   genres    6000 non-null   object
 4   keywords  6000 non-null   object
 5   rating    6000 non-null   float64
 6   combined  1000 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 328.3+ KB

None

📊 Basic Statistics (numeric columns):

           movie_id       rating
count  6.000000e+03  6000.000000
mean   3.996660e+05     2.510772
std    4.101912e+05     1.153219
min    8.800000e+01     1.000000
25%    4.581200e+04     1.550000
50%    2.747900e+05     2.170000
75%    6.229340e+05     3.410000
max    1.477829e+06     5.000000

🧪 Sample Rows:

,user_id,movie_id,title,genres,keywords,rating,combined
1063,user_43,586893,Kolaigaran,"Crime, Thriller, Drama, Action","psychopath, murder, murder investigation",1.09,NaN
4744,user_190,16119,Cinderella III: A Twist in Time,"Romance, Family, Fantasy, Animation","sequel, fairy godmother, prince, fairy, musica...",2.86,NaN
3514,user_141,1131303,Hunter's Refuge,"Documentary, History, Comedy","nature, social, character driven, hunting, com...",1.70,NaN
4208,user_169,389364,12th Hitlerjugend Panzer Division,"War, Documentary, History","d-day, world war ii, normandy, france, ss (naz...",1.91,NaN
5493,user_188,474512,Coral Reef Legend: Elfie of the Blue Sea,"TV Movie, Adventure, Drama, Family, Fantasy, A...",anime,4.67,"tv movie, adventure, drama, family, fantasy, a..."

In [9]:
user_counts = users_df.groupby('user_id').size()
user_counts

user_id
user_1      30
user_10     30
user_100    30
user_101    30
user_102    30
            ..
user_95     30
user_96     30
user_97     30
user_98     30
user_99     30
Length: 200, dtype: int64

##NOTE Generate numeric identifier: LightFM python only except numeric id

In [10]:
import pandas as pd

def generate_int_id(df: pd.DataFrame, col_name: str, new_col_name: str = None) -> pd.DataFrame:
    """
    Convert a string/categorical column into unique integer IDs.

    Parameters
    ----------
    df : pd.DataFrame
        Input DataFrame.
    col_name : str
        Name of the column to encode (e.g. 'user_id' or 'movie_id').
    new_col_name : str, optional
        Name of the new column to store integer IDs.
        - If provided: a new column is created.
        - If None: the original column is overwritten.

    Returns
    -------
    pd.DataFrame
        DataFrame with the encoded integer column.
    """

    # Factorize the column: assigns a unique integer to each unique value
    # e.g. ['u1', 'u2', 'u1'] → [0, 1, 0]
    codes, uniques = pd.factorize(df[col_name])

    # Determine where to store the result:
    # - Use new_col_name if provided
    # - Otherwise overwrite the original column
    target_col = new_col_name if new_col_name is not None else col_name

    # Store the encoded values in the target column
    df[target_col] = codes.astype('int64')

    return df

In [11]:
users_df = generate_int_id(users_df, "user_id")
users_df.head()

,user_id,movie_id,title,genres,keywords,rating,combined
0,0,386564,"Hang in There, Kids!","Drama, Family, Comedy",woman director,3.08,NaN
1,0,67077,The Plane Tree,"Drama, Family, Comedy",woman director,3.59,NaN
2,0,189005,Pennies from Heaven,"Drama, Music, Comedy","welfare, singer, welfare worker",2.91,NaN
3,0,154764,Miyamoto Musashi,"Drama, History, Action","jidaigeki, miyamoto musashi, chambara",3.20,NaN
4,0,512062,Vinayapoorvam Vidyadharan,"Drama, Family, Comedy","dysfunctional marriage, romance",3.79,NaN

# Buildinf the ID mapping

# Data Preparation

In [12]:
from lightfm.data import Dataset

Note that if we don’t have all user and items ids at once, we can repeatedly call fit_partial to supply additional ids. In this case, we will use this capability to add some item feature mappings:

# Item Features

In [13]:
### TODO Rewrite Function
def extract_item_feature_list(df, feature_columns):
    """
    Extract unique lowercase feature values from selected metadata columns.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing movie metadata.
    feature_columns : list of str
        Column names to extract features from.

    Returns
    -------
    Set[str]
        Set of all unique feature names (lowercased).
    """
    movie_all_features = set()
    for _, row in df.iterrows():
        combined = []
        for col in feature_columns:
            combined.extend(str(row[col]).split(','))
        cleaned = [f.strip().lower() for f in combined if f.strip()]
        movie_all_features.update(cleaned)
    return  list(movie_all_features)

In [14]:
# SAME AS extract_item_feature_list but Generator function
# def generate_split_item_features(df, feature_columns):
#     """
#     Yield unique, cleaned feature strings from specified metadata columns in the DataFrame.

#     This is a generator function that iterates over each row and each listed feature
#     column (e.g. 'genres', 'keywords'), splitting comma-delimited strings into individual
#     tokens, then lowercasing and stripping whitespace. Each distinct feature is yielded
#     exactly once, making it efficient for use in large-scale feature registration.

#     Parameters
#     ----------
#     df : pandas.DataFrame
#         DataFrame containing item metadata. Feature columns must contain comma-separated
#         strings representing feature lists.

#         Example:
#         --------
#         genres   → "Action, Adventure, Sci-Fi"
#         keywords → "space, alien, galaxy"

#     feature_columns : list of str
#         Column names in `df` to extract features from (e.g. ['genres', 'keywords']).

#     Yields
#     ------
#     str
#         A cleaned, lowercase feature string. Duplicates are skipped. Unique features
#         are streamed one-by-one and not stored as a list in memory.

#     Examples
#     --------
#     >>> for feature in generate_item_features(movies_df, ['genres', 'keywords']):
#     ...     print(feature)
#     'action'
#     'adventure'
#     'sci-fi'
#     'space'
#     'alien'
#     'galaxy'
#     ...
#     """
#     seen = set()
#     for _, row in df.iterrows():
#         for col in feature_columns:
#             for raw in str(row[col]).split(','):
#                 feature = raw.strip().lower()
#                 if feature and feature not in seen:
#                     seen.add(feature)
#                     yield feature


# dataset.fit_partial(
#     items=movies_df['movie_id'],
#     item_features=generate_split_item_features(movies_df, ['genres', 'keywords'])
# )

In [15]:
# def generate_simple_features(df, feature_columns):
#     """
#     Generator function: yields unique lowercase feature values from simple string columns.

#     This function is designed for feature columns where each row contains a single string value,
#     such as author names, country, language, etc. Unlike genres or keywords, the strings are not
#     comma-separated or lists — just plain values. The function lowercases and strips whitespace,
#     yielding each unique value exactly once.

#     Parameters
#     ----------
#     df : pandas.DataFrame
#         DataFrame containing item metadata with simple string feature columns.

#         Example:
#         --------
#         author_column → "Dan Brown"
#         language      → "English"

#     feature_columns : list of str
#         Column names to extract features from (e.g. ['author_column', 'language']).

#     Yields
#     ------
#     str
#         A cleaned, lowercase feature string. Each distinct value is yielded once.

#     Examples
#     --------
#     >>> for feature in generate_simple_features(movies_df, ['author_column']):
#     ...     print(feature)
#     'dan brown'
#     'j.k. rowling'
#     'isaac asimov'
#     ...
#     """
#     seen = set()
#     for _, row in df.iterrows():
#         for col in feature_columns:
#             feature = str(row[col]).strip().lower()
#             if feature and feature not in seen:
#                 seen.add(feature)
#                 yield feature

In [16]:
def build_item_feature_tuples(df, feature_columns):
    """
    Build (movie_id, [features...]) tuples for LightFM item_features.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing movie metadata.
    feature_columns : list of str
        Columns to use for feature extraction.

    Returns
    -------
    List[Tuple[int, List[str]]]
        Tuples of movie_id and its feature list.
    """
    tuples = []
    for _, row in df.iterrows():
        combined = []
        for col in feature_columns:
            combined.extend(str(row[col]).split(','))
        cleaned = [f.strip().lower() for f in combined if f.strip()]
        tuples.append((row['movie_id'], cleaned))
    return tuples

In [17]:
from lightfm.data import Dataset

# Step 1: Prepare dataset
dataset = Dataset()
dataset.fit(users_df['user_id'], movies_df['movie_id'])

num_users, num_items = dataset.interactions_shape()
print('Num users: {}, num_items {}.'.format(num_users, num_items))

Num users: 200, num_items 135886.

In [18]:
### TODO Rewrite Function
# Step 2: Extract feature set and fit dataset
feature_columns = ['genres', 'keywords']
movie_all_features = extract_item_feature_list(movies_df, feature_columns)
dataset.fit_partial(items=movies_df['movie_id'], item_features=movie_all_features)

# TODO check build_item_features parameter format
# Step 3: Build item_features matrix
item_feature_tuples = build_item_feature_tuples(movies_df, feature_columns)
item_features = dataset.build_item_features(item_feature_tuples)

In [19]:
num_users, num_items = dataset.interactions_shape()
print('Num users: {}, num_items {}.'.format(num_users, num_items))

Num users: 200, num_items 135886.

In [20]:
import pandas as pd
import numpy as np

def split_user_interactions_df(df, user_col='user_id', test_size=0.2, random_state=42):
    """
    Optimized version: split each user's interactions into train and test sets.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame with user-item interactions.
    user_col : str
        Column for user ID.
    test_size : float
        Fraction of each user's data to put into test.
    random_state : int
        Random seed for reproducibility.

    Returns
    -------
    train_df : pd.DataFrame
    test_df : pd.DataFrame
    """
    rng = np.random.default_rng(random_state)

    # Assign a row number within each user group
    df = df.copy()
    df['_row_id'] = df.groupby(user_col).cumcount()

    # Count interactions per user
    user_counts = df.groupby(user_col)['_row_id'].max() + 1

    test_rows = []
    for user_id, count in user_counts.items():
        if count < 2:
            continue
        test_size_u = max(1, int(count * test_size))
        test_indices = rng.choice(count, size=test_size_u, replace=False)
        test_rows.extend(df[(df[user_col] == user_id) & (df['_row_id'].isin(test_indices))].index)

    test_df = df.loc[test_rows].drop(columns=['_row_id'])
    train_df = df.drop(index=test_rows).drop(columns=['_row_id'])

    return train_df.reset_index(drop=True), test_df.reset_index(drop=True)

In [21]:
# Split your DataFrame:
# train_user_df, test_user_df = split_user_interactions_df(df=users_df,user_col='user_id', test_size=0.2, random_state=42)

In [22]:
# display(train_user_df.head())
# display(train_user_df.tail())

In [23]:
# display(test_user_df.head())
# display(test_user_df.tail())

In [24]:
# user_counts = train_user_df.groupby('user_id').size()
# user_counts

In [25]:
# user_counts = test_user_df.groupby('user_id').size()
# user_counts

In [26]:
# train_user_df.shape

In [27]:
# test_user_df.shape

In [28]:
# Build train interaction matrix
# (train_interactions, train_weights) = dataset.build_interactions([
#     (u, i, 1.0)
#     for u, i, r in zip(train_user_df['user_id'], train_user_df['movie_id'], train_user_df['rating'])
# ])

# # Build test interaction matrix
# (test_interactions, test_weights) = dataset.build_interactions([
#     (u, i, 1.0)
#     for u, i, r in zip(test_user_df['user_id'], test_user_df['movie_id'], test_user_df['rating'])
# ])

In [68]:
# (interactions, weights) = dataset.build_interactions([
#     (u, i, r) for u, i, r in zip(users_df['user_id'], users_df['movie_id'], users_df['rating'])
# ])

(interactions, weights) = dataset.build_interactions([
    (u, i, 1.0)
    for u, i, r in zip(users_df['user_id'], users_df['movie_id'], users_df['rating'])
])

# (interactions, weights) = dataset.build_interactions([
#     (u, i, 1.0 if r >= 3.5 else 0.0) # user rating more than 3.0 ==
#     for u, i, r in zip(users_df['user_id'], users_df['movie_id'], users_df['rating'])
# ])

In [69]:
from lightfm.cross_validation import random_train_test_split

# Split both interactions and weights into train/test
train_interactions, test_interactions = random_train_test_split(interactions, test_percentage=0.2, random_state=42)
train_weights, test_weights = random_train_test_split(weights, test_percentage=0.2, random_state=42)

In [70]:
from lightfm import LightFM

# 3. Train the model using only the training interactions and corresponding weights
model = LightFM(
    loss='warp' # warp , bpr, logistic
)

model.fit(
    interactions=train_interactions,
    item_features=item_features,
    sample_weight=train_weights,
    epochs=20,
)

# Evaluation

In [71]:
from lightfm.evaluation import precision_at_k, recall_at_k, auc_score

k = 3

precision_scores = precision_at_k(
    model, train_interactions,
    item_features=item_features, k=k).mean()

recall_scores = recall_at_k(
    model, train_interactions,
    item_features=item_features, k=k).mean()

auc = auc_score(
    model, train_interactions,
    item_features=item_features).mean()

print("TRAIN")
print(f"Precision@{k}: {precision_scores:.4f}")
print(f"Recall@{k}: {recall_scores:.4f}")
print(f"AUC: {auc:.4f}")

TRAIN
Precision@3: 0.4650
Recall@3: 0.0588
AUC: 0.9885

In [72]:
from lightfm.evaluation import precision_at_k, recall_at_k, auc_score

k = 5

precision_scores = precision_at_k(
    model, train_interactions,
    item_features=item_features, k=k).mean()

recall_scores = recall_at_k(
    model, train_interactions,
    item_features=item_features, k=k).mean()

auc = auc_score(
    model, train_interactions,
    item_features=item_features).mean()

print("TRAIN")
print(f"Precision@{k}: {precision_scores:.4f}")
print(f"Recall@{k}: {recall_scores:.4f}")
print(f"AUC: {auc:.4f}")

TRAIN
Precision@5: 0.4040
Recall@5: 0.0852
AUC: 0.9885

In [73]:
from lightfm.evaluation import precision_at_k, recall_at_k, auc_score

k = 3

precision_scores = precision_at_k(
    model, test_interactions, train_interactions=train_interactions,
    item_features=item_features, k=k).mean()
recall_scores = recall_at_k(
    model, test_interactions, train_interactions=train_interactions,
    item_features=item_features, k=k).mean()
auc = auc_score(
    model, test_interactions, train_interactions=train_interactions,
    item_features=item_features).mean()

print(f"TEST")
print(f"Precision@{k}: {precision_scores:.4f}")
print(f"Recall@{k}: {recall_scores:.4f}")
print(f"AUC: {auc:.4f}")

TEST
Precision@3: 0.1433
Recall@3: 0.0692
AUC: 0.9462

In [74]:
from lightfm.evaluation import precision_at_k, recall_at_k, auc_score

k = 5

precision_scores = precision_at_k(
    model, test_interactions, train_interactions=train_interactions,
    item_features=item_features, k=k).mean()
recall_scores = recall_at_k(
    model, test_interactions, train_interactions=train_interactions,
    item_features=item_features, k=k).mean()
auc = auc_score(
    model, test_interactions, train_interactions=train_interactions,
    item_features=item_features).mean()

print(f"TEST")
print(f"Precision@{k}: {precision_scores:.4f}")
print(f"Recall@{k}: {recall_scores:.4f}")
print(f"AUC: {auc:.4f}")

TEST
Precision@5: 0.1070
Recall@5: 0.0865
AUC: 0.9462

In [75]:
from lightfm.evaluation import precision_at_k, recall_at_k, auc_score

k = 6

precision_scores = precision_at_k(
    model, test_interactions, train_interactions=train_interactions,
    item_features=item_features, k=k).mean()
recall_scores = recall_at_k(
    model, test_interactions, train_interactions=train_interactions,
    item_features=item_features, k=k).mean()
auc = auc_score(
    model, test_interactions, train_interactions=train_interactions,
    item_features=item_features).mean()

print(f"TEST")
print(f"Precision@{k}: {precision_scores:.4f}")
print(f"Recall@{k}: {recall_scores:.4f}")
print(f"AUC: {auc:.4f}")

TEST
Precision@6: 0.0975
Recall@6: 0.0947
AUC: 0.9462

In [76]:
# from lightfm.evaluation import precision_at_k, recall_at_k, auc_score

# k = 10

# precision_scores = precision_at_k(
#     model, test_interactions, train_interactions=train_interactions,
#     item_features=item_features, k=k).mean()
# recall_scores = recall_at_k(
#     model, test_interactions, train_interactions=train_interactions,
#     item_features=item_features, k=k).mean()
# auc = auc_score(
#     model, test_interactions, train_interactions=train_interactions,
#     item_features=item_features).mean()

# print(f"TEST")
# print(f"Precision@{k}: {precision_scores:.4f}")
# print(f"Recall@{k}: {recall_scores:.4f}")
# print(f"AUC: {auc:.4f}")

# Prediction

In [77]:
import numpy as np

def sample_recommendation(model, dataset, interactions, item_features,
                          user_ids, movies_df, top_n=5):
    """
    Show known positives and top-N recommendations with scores for each user.

    Parameters:
    - model: Trained LightFM model
    - dataset: LightFM dataset object (needed to extract mappings)
    - interactions: Sparse interaction matrix
    - item_features: Sparse matrix of item metadata
    - user_ids: List of actual user IDs (external IDs)
    - movies_df: DataFrame with 'movie_id' and 'title'
    - top_n: Number of recommendations to return per user

    Returns:
    - Dict with user_id as key and list of top-N recommendations as value
    """
    user_id_map, _, item_id_map, _ = dataset.mapping()
    item_id_inv_map = {v: k for k, v in item_id_map.items()}

    def get_seen_movie_ids(uidx):
        seen_indices = interactions.tocsr()[uidx].indices
        return [item_id_inv_map[i] for i in seen_indices]

    def get_movie_info(movie_id):
        row = movies_df[movies_df['movie_id'] == movie_id]
        if row.empty:
            return {"title": "Unknown", "genres": "N/A", "keywords": "N/A"}
        row = row.iloc[0]
        return {
            "title": row.get("title", "Unknown"),
            "genres": row.get("genres", "N/A"),
            "keywords": row.get("keywords", "N/A")
        }

    results = {}

    for user_id in user_ids:
        if user_id not in user_id_map:
            print(f"User {user_id} not found in training set.\n")
            continue

        uidx = user_id_map[user_id]
        n_items = interactions.shape[1]

        seen_movie_ids = get_seen_movie_ids(uidx)
        known_titles = movies_df[movies_df['movie_id'].isin(seen_movie_ids)]['title'].tolist()

        scores = model.predict(uidx, np.arange(n_items), item_features=item_features)
        top_indices = np.argsort(-scores)[:top_n]

        # === DEBUG ===
        print(f"\n🎯 User: {user_id}")
        print("✅ Known positives:")
        for movie_id in seen_movie_ids[:min(len(seen_movie_ids), 100)]:
            info = get_movie_info(movie_id)
            print(f"   • {info['title']}")
            print(f"     Genres: {info['genres']}")
            print(f"     Keywords: {info['keywords']}")

        print(f"🔮 Top {top_n} Recommendations:")
        user_recommendations = []
        for idx in top_indices:
            movie_id = item_id_inv_map[idx]
            info = get_movie_info(movie_id)
            score = round(scores[idx], 4)

            print(f"   • {info['title']} (score: {score})")
            print(f"     Genres: {info['genres']}")
            print(f"     Keywords: {info['keywords']}")

            user_recommendations.append({
                "movie_id": movie_id,
                "title": info["title"],
                "genres": info["genres"],
                "keywords": info["keywords"],
                "score": score
            })

        results[user_id] = user_recommendations

    return results

In [78]:
sample_recommendation(
    model=model,
    dataset=dataset,
    interactions=train_interactions,
    item_features=item_features,
    user_ids=[0],
    movies_df=movies_df,
    top_n=10
)

🎯 User: 0
✅ Known positives:
   • Hedwig and the Angry Inch
     Genres: Drama, Music, Comedy
     Keywords: lgbt in the military, self identity, glam rock, singer, child molestation, transsexuality, restaurant chain, nonbinary director, military brat, lgbt, rock odyssey, transvestism, theatrical manager
   • (Nie)znajomi
     Genres: Drama, Comedy
     Keywords: man woman relationship, father daughter relationship, husband wife relationship, lgbt, mother daughter relationship, friendship, remake
   • Charlotte's Web
     Genres: Drama, Family, Animation, Music, Comedy
     Keywords: spider web, talking pig, musical, anthropomorphism, friendship, cartoon spider
   • Sidekicks
     Genres: Adventure, Drama, Family, Action
     Keywords: asthmatic, gym instructor, martial arts training, computer programmer, bully, nunchaku, parent teacher romance, student mentor relationship, training-montage, daydreaming, martial arts, martial arts tournament, chinese restaurant, karate
   • Lo Steinway
     Genres: Drama, War, History, Animation
     Keywords: truce, great war, piano
   • Emperor Meiji and General Nogi
     Genres: Drama, War, History
     Keywords: japan, history of japan, russo-japanese war, imperial japan
   • Private Detective DOBU 4: The Mysterious Kite Murders Case
     Genres: Drama, History, Action
     Keywords: jidaigeki
   • The Notorious Bored Samurai 3
     Genres: Drama, History, Action
     Keywords: jidaigeki
   • Tatara Samurai
     Genres: Drama, War, History, Comedy, Action
     Keywords: samurai, chanbara
   • The Ode to Joy
     Genres: Drama, War, History, Music
     Keywords: japan, germany
   • Hot Rhythm
     Genres: Romance, War, Music, Comedy
     Keywords: record company, singer, radio, contract
   • By the Ravine
     Genres: Drama, War, History
     Keywords: woman director
   • Pennies from Heaven
     Genres: Drama, Music, Comedy
     Keywords: welfare, singer, welfare worker
   • Hang in There, Kids!
     Genres: Drama, Family, Comedy
     Keywords: woman director
   • The Samurai in Autumn
     Genres: Drama, Comedy, Action
     Keywords: samurai, sports, fighter, romance, karate
   • Miyamoto Musashi VI: Swords of Death
     Genres: Drama, History, Action
     Keywords: jidaigeki, miyamoto musashi, chambara
   • Marble Ass
     Genres: Drama, War, Comedy
     Keywords: prostitute, lgbt, transvestism
   • Capricious Young Man
     Genres: Drama, History, Comedy
     Keywords: jidaigeki, samourai, romance, shogun
   • 1971: Beyond Borders
     Genres: Drama, War
     Keywords: rescue, letter, relationship, family, united nations, india pakistan war, tank, friendship, gun fight
   • Lady Maiko
     Genres: Drama, Music, Comedy
     Keywords: japan, geisha, coming of age, kyoto, maiko
   • Kochavva Paulo Ayyappa Coelho
     Genres: Drama
     Keywords: swimmer, airplane, wish, tournament, child
   • Growing Pains: Return of the Seavers
     Genres: Drama, Family, Comedy
     Keywords: tv series reunion, woman director, return
   • Hotel Very Welcome
     Genres: Drama
     Keywords: travel, backpacker, thailand, goa, relationship, woman director, sense of life
   • The Plane Tree
     Genres: Drama, Family, Comedy
     Keywords: woman director
   • All the Queen's Men
     Genres: Drama, War, History, Comedy, Action
     Keywords: world war ii, transvestism
🔮 Top 10 Recommendations:
   • Eight Women Fighters (score: 1.420199990272522)
     Genres: War, History
     Keywords: world war ii
   • By the Ravine (score: 1.3387999534606934)
     Genres: Drama, War, History
     Keywords: woman director
   • The Other Way (score: 1.2858999967575073)
     Genres: War, History
     Keywords: world war ii
   • Paths of War (score: 1.1155999898910522)
     Genres: Drama, War, History
     Keywords: world war ii, resistance, black and white, war
   • Go for Broke! (score: 1.0844000577926636)
     Genres: Drama, War, History, Action
     Keywords: army, world war ii
   • April 9th (score: 1.0240000486373901)
     Genres: Drama, War, History
     Keywords: world war ii, historical battle, war
   • The Fighting Sullivans (score: 0.9990000128746033)
     Genres: Drama, War, History
     Keywords: biography, world war ii
   • In the Name of the Motherland (score: 0.9758999943733215)
     Genres: Drama, War, History
     Keywords: world war ii
   • Festín para la muerte (score: 0.9602000117301941)
     Genres: Drama, War, History
     Keywords: world war ii
   • The Liberation of Prague (score: 0.9415000081062317)
     Genres: Drama, War, History
     Keywords: world war ii

{0: [{'movie_id': 412254,
   'title': 'Eight Women Fighters',
   'genres': 'War, History',
   'keywords': 'world war ii',
   'score': np.float32(1.4202)},
  {'movie_id': 263838,
   'title': 'By the Ravine',
   'genres': 'Drama, War, History',
   'keywords': 'woman director',
   'score': np.float32(1.3388)},
  {'movie_id': 1069560,
   'title': 'The Other Way',
   'genres': 'War, History',
   'keywords': 'world war ii',
   'score': np.float32(1.2859)},
  {'movie_id': 393153,
   'title': 'Paths of War',
   'genres': 'Drama, War, History',
   'keywords': 'world war ii, resistance, black and white, war',
   'score': np.float32(1.1156)},
  {'movie_id': 37214,
   'title': 'Go for Broke!',
   'genres': 'Drama, War, History, Action',
   'keywords': 'army, world war ii',
   'score': np.float32(1.0844)},
  {'movie_id': 332179,
   'title': 'April 9th',
   'genres': 'Drama, War, History',
   'keywords': 'world war ii, historical battle, war',
   'score': np.float32(1.024)},
  {'movie_id': 43504,
   'title': 'The Fighting Sullivans',
   'genres': 'Drama, War, History',
   'keywords': 'biography, world war ii',
   'score': np.float32(0.999)},
  {'movie_id': 467893,
   'title': 'In the Name of the Motherland',
   'genres': 'Drama, War, History',
   'keywords': 'world war ii',
   'score': np.float32(0.9759)},
  {'movie_id': 1364553,
   'title': 'Festín para la muerte',
   'genres': 'Drama, War, History',
   'keywords': 'world war ii',
   'score': np.float32(0.9602)},
  {'movie_id': 311004,
   'title': 'The Liberation of Prague',
   'genres': 'Drama, War, History',
   'keywords': 'world war ii',
   'score': np.float32(0.9415)}]}